services:
  frontend:
    build:
      context: ../  # Esto apunta a la carpeta 'frontend'
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ../backend  # Esto apunta a la carpeta 'backend'
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
      MYSQL_DATABASE: flaskdb
    networks:
      - mynetwork
  
  nginx:
    build:
      context: ../nginx  # Apunta a 'frontend/nginx' desde 'src'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
    networks:
      - mynetwork

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge
