auth_enabled: false
server:
  http_listen_port: 3100
positions:
  filename: /tmp/positions.yaml
schema_config:
  configs:
    - from: 2023-04-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
